Odległość do najbliższego oddziału =
/*
SCENARIUSZ:
    Zwraca odległość w km od aktualnego oddziałudo najbliższego INNEGO oddziału.

WYMAGANIA WSTĘPNE:
    1. 1 wiersz w dim_Oddziały = 1 oddział.
    2. Każdy analizowany oddział posiada współrzędne.
    3. Miara działa w kontekście pojedynczego oddziału.
    4. Odległość liczona jest wzorem Haversine.
    5. Wynik jest odległością w linii prostej.
    
WYDAJNOŚĆ:
    - MINX znajduje minimum bez potrzeby sortowania tabeli.
    - Nie używamy TOPN, ponieważ interesuje nas tylko wartość minimalnej odległości.
*/

VAR Lat1 =  SELECTEDVALUE ( dim_Oddziały[szerokość_geograficzna] )
VAR Lon1 =  SELECTEDVALUE ( dim_Oddziały[długość_geograficzna] )
VAR Oddzial =  SELECTEDVALUE ( dim_Oddziały[nazwa_oddziału] )
VAR Lat1Rad =  RADIANS ( Lat1 )
VAR Lon1Rad = RADIANS ( Lon1 )
VAR PozostaleOddzialy =
    FILTER (
        ALL ( dim_Oddziały ),
        dim_Oddziały[nazwa_oddziału] <> Oddzial
    )

RETURN
    MINX (
        PozostaleOddzialy,
        VAR Lat2Rad =  RADIANS ( dim_Oddziały[szerokość_geograficzna] )
        VAR Lon2Rad =   RADIANS ( dim_Oddziały[długość_geograficzna] )
        VAR DLat = Lat2Rad - Lat1Rad
        VAR DLon = Lon2Rad - Lon1Rad
        VAR A =  POWER ( SIN ( DLat / 2 ), 2 )  + COS ( Lat1Rad )  * COS ( Lat2Rad )  * POWER ( SIN ( DLon / 2 ), 2 )

        RETURN
            6371  * 2 * ASIN ( SQRT ( A ) )
    )
